;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	electric-pair-delete-pair
	haml-electric-backspace
	))

(setq mc/cmds-to-run-once
      '(
	backward-delete-char
	backward-kill-sentence
	lsp-ui-doc--handle-mouse-movement
	))
